spring:
  application:
    name: grpc-trial-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: ${EUREKA_REGISTRATION_PORT:22231}
  grpc:
    port: 7849

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2012/eureka}
  instance:
    preferIpAddress: true
